services:
  # 1. Backend API (Django)
  backend:
    build: ./backend
    container_name: nms_backend
    restart: always
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - TZ=Asia/Jakarta  # Tambahkan ini
    env_file: .env
    networks:
      - nms_network

  # 2. MQTT Listener (Worker Background)
  mqtt_listener:
    build: ./backend
    container_name: nms_mqtt_worker
    restart: always
    # Menjalankan command custom management file Anda
    command: python manage.py mqtt_listener 
    environment:
      - TZ=Asia/Jakarta  # Tambahkan ini
    env_file: .env
    depends_on:
      - backend
    networks:
      - nms_network

  # 3. Frontend (React)
  frontend:
    build: ./frontend
    container_name: nms_frontend
    restart: always
    networks:
      - nms_network

  # 4. Nginx (Gateway Utama)
  nginx:
    image: nginx:alpine
    container_name: nms_nginx
    restart: always
    ports:
      # Format: "PORT_VPS:PORT_CONTAINER"
      # Ini akan membuka port sesuai settingan di .env
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - nms_network

volumes:
  static_volume:
  media_volume:

networks:
  nms_network:
    driver: bridge